apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/balagcpcloud/gitops-k8s-platform
    targetRevision: main
    path: apps/tomcat
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
